### ISSUE TITLE
Addon failed to load

### ISSUE THREAD

**Issue by cybrzwerg** [BigFatDuck1/boldcolorshortcut-anki#1]
After installing the addon and restarting Anki I got following error:
![image](https://user-images.githubusercontent.com/82151392/117546004-86b32580-b028-11eb-9f35-bbcfddc9e4a7.png)
The Addon "Quick Colour Changing" is working on the same system while the highlightig addon causes the same error.

**Comment by BigFatDuck1** [comment]
Hi, 
what system are you running anki on? 

Also, does it work if you uninstall "Quick Colour Changing"? Since the functionality is near identical there may be a clash with the addons - if you do not want the words to be bolded you can set it in the config file, or alternatively unbold the word (ctrl + b) after applying the keyboard shortcut (the color will still remain, only the bold will be removed).

**Comment by cybrzwerg** [comment]
System: Pop!_OS 20.04 LTS x86_64 with Python 2.7.18 and 3.8.5.
Toggling "Quick Colour Changing" to disabled as well as uninstalling it doesn't solve the issue.

**Comment by BigFatDuck1** [comment]
Thanks! May I ask what version of anki are you using?

**Comment by cybrzwerg** [comment]
Version 2.1.15 (442df9d6)
Qt 5.12.8 PyQt 5.14.1

**Comment by BigFatDuck1** [comment]
I see! The add-on uses the new style of hooks (https://addon-docs.ankiweb.net/#/hooks-and-filters?id=new-style-hooks), which was added in Anki 2.1.20 - are you using 2.1.15 for a specific reason?

**Comment by cybrzwerg** [comment]
Turns out I just missed the update. Thanks for helping out (and for creating the addons in the first place).

**Comment by BigFatDuck1** [comment]
Thank you! Let me know if anything else arises!
